version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3306:3306
    volumes:
      - ~/dev/docker/mysql/mysql_nestjs:/var/lib/mysql